### ISSUE TITLE
problem loading the icons

### ISSUE THREAD

**Issue by ghost** [baronleonardo/mailchecker#12]
Traceback (most recent call last):
  File "mail_checker.py", line 256, in save_new_mail_data
    self.construct()
  File "mail_checker.py", line 55, in construct
    self.tray_icon = self.create_tray_icon()
  File "mail_checker.py", line 146, in create_tray_icon
    self.current_path + self.settings_data["zero_messages_tray_icon"])
TypeError: 'NoneType' object has no attribute '**getitem**'

**Comment by baronleonardo** [comment]
Solved now
