### ISSUE TITLE
can't add an email

### ISSUE THREAD

**Issue by ghost** [baronleonardo/mailchecker#23]
i deleted the db and I'm trying to add my emails but it won't let me.
here's the log:

```
load settings
right click
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
Add new mail data
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
Save new mail data
Traceback (most recent call last):
  File "mail_checker.py", line 382, in save_new_mail_data
    self.database.insert(mail_data)
  File "/home/adam/Workspace/mailchecker/db_controller.py", line 71, in insert
    " VALUES (?,?,?,?);", data)
sqlite3.OperationalError: 4 values for 5 columns
```

**Comment by baronleonardo** [comment]
Solved
